server:
  port: 8088
spring:
  redis:
    host: 192.168.80.130
  application:
    name: cart-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
leyou:
  jwt:
    pubKeyPath: D:\\WorkSpas\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
