server:
  port: 8761
spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: leyou-resgistry
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false


  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
